before_script:
  - npm install -g gulp
  - npm rebuild node-sass
script: gulp
deploy:
  provider: releases
    api_key:
      secure: "Rz927vEfT8gRNvkAXjphRYjEehXTT3lKscdL8Rfz3EHFC9gQ4ecvcvRUdl973uXZe4n29xrAQXjIqLQwqfEgrJy0LDmLQIfysDdi6FDvwqpf10mGTQhNlsHD/Ep7dSgyszu9esgVRQbHHZRGZhP1132HV1trmVVpFsvI2zHy7GOFVp3Ov1qrrnmZ1pYvNMrq979uCRq7mQYTznDZpfIY6J20KVpXU5N+ojU7lRp040oAvjhFAtZWzZFSnFdEJkLelhhV4KGPELLAcs4F83dtGM2RIEBHxCz6ED4JV6mf4DsryfA607/62nklNHXsr3l7BcMYtCTR7m+UHbr7uebWvtRRgs++j2mdSUeg2BoGqg6W/4GZ2tM0dgaXhitH9OcZQ6rRKq7gsvWWv4kMdV0jO5dvyKoFnTJqfcawC6VtVKcoWnK2DJK59zVWJ+LGTDL5D+chr+0fBk3Ypm22ZOTnZeDtvyeJ9RoRiJt7cw64qjVTKTA57pkLCRw23cjMVBylsO6AlEfIp2XLpPcYbQruxLdqIojqJGZvcg7iT2PoAGqDfWXmpi2o4VVltVgBeVHCDGFwhFGe+F412jH02WNiqmS9JE6EBTXCSC332TtJNNG43yvA1d7r3DrjlctR6h7PVkPssr/+UNQhvfija/+DpTaxySR/zXCl6L0zoUyR91M="
